[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 301
  force = true
  query = {path = ":path"}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/customer"
  to = "/customer"
  status = 301
  force = true # COMMENT: ensure that we always redirect


## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/engineer"
  to = "/engineer"
  status = 301
  force = true # COMMENT: ensure that we always redirect
